export const FETCH_CHECKOUT_FIELDS_OK = 'FETCH_CHECKOUT_FIELDS_OK';
export const FETCH_CHECKOUT_FIELDS_REJECTED = 'FETCH_CHECKOUT_FIELDS_REJECTED';

export const FETCH_SHIPPING_METHODS_OK = 'FETCH_SHIPPING_METHODS_OK';
export const FETCH_SHIPPING_METHODS_REJECTED = 'FETCH_SHIPPING_METHODS_REJECTED';

export const SUBMIT_ORDER_OK = 'SUBMIT_ORDER_OK';
export const SUBMIT_ORDER_REJECTED = 'SUBMIT_ORDER_REJECTED';

export const CHECKOUT_LOAD = 'CHECKOUT_LOAD';
