export const FETCH_PRODUCTS_LOAD = 'FETCH_PRODUCTS_LOAD';
export const FETCH_PRODUCTS_OK = 'FETCH_PRODUCTS_OK';
export const FETCH_PRODUCTS_REJECTED = 'FETCH_PRODUCTS_REJECTED';

export const FETCH_SINGLE_PRODUCT_OK = 'FETCH_SINGLE_PRODUCT_OK';
export const FETCH_SINGLE_PRODUCT_REJECTED = 'FETCH_SINGLE_PRODUCT_REJECTED';

export const CART_UPDATE_EVENT = 'CART_UPDATE_EVENT';

