export const USER_LOAD = 'USER_LOAD';
export const USER_LOGOUT = 'USER_LOGOUT';

export const LOGIN_OK = 'LOGIN_OK';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';

export const REGISTER_OK = 'REGISTER_OK';
export const REGISTER_REJECTED = 'REGISTER_REJECTED';

export const FETCH_ORDERS_LOAD = 'FETCH_ORDERS_LOAD';
export const FETCH_ORDERS_OK = 'FETCH_ORDERS_OK';
export const FETCH_ORDERS_REJECTED = 'FETCH_ORDERS_REJECTED';


export const FETCH_ORDER_ITEMS_LOAD = 'FETCH_ORDER_ITEMS_LOAD';

export const FETCH_ORDER_ITEMS_OK = 'FETCH_ORDER_ITEMS_OK';
export const FETCH_ORDER_ITEMS_REJECTED = 'FETCH_ORDER_ITEMS_REJECTED';
